# Generated by Django 3.0.3 on 2020-03-29 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=45)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name_category'],
            },
        ),
        migrations.CreateModel(
            name='AdTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name_tag'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(max_length=1500)),
                ('priority', models.CharField(choices=[('3', 'High'), ('2', 'Medium'), ('1', 'Low')], default='2', max_length=10)),
                ('location_country', models.CharField(max_length=50)),
                ('location_city', models.CharField(max_length=50)),
                ('location_postcode', models.CharField(max_length=10)),
                ('typeAd', models.CharField(choices=[('OF', 'Offered'), ('WA', 'Wanted')], default='OF', max_length=10)),
                ('external', models.BooleanField(blank=True, default=False)),
                ('external_link', models.CharField(blank=True, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('date_external', models.DateTimeField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('categories', models.ManyToManyField(to='ads.AdCategory')),
                ('images', models.ManyToManyField(to='images.Image')),
                ('tags', models.ManyToManyField(to='ads.AdTag')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
